version: 2.1

executors:
  go-docker:
    docker:
      - image: cimg/go:1.24.4

jobs:
  test:
    executor: go-docker
    steps:
      - checkout
      - run: go test ./...

  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build --platform linux/amd64 -t $DOCKERHUB_USERNAME/feedback-service:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/feedback-service:latest

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Helm & Kubectl
          command: |
            curl -LO https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
            tar -zxvf helm-v3.14.4-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin/helm

            curl -LO "https://dl.k8s.io/release/v1.31.1/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/

      - run:
          name: Set up kubeconfig
          command: |
            echo $KUBECONFIG_CONTENT | base64 -d > kubeconfig.yaml
            export KUBECONFIG=$(pwd)/kubeconfig.yaml
            kubectl get nodes

      - run:
          name: Deploy with Helm
          command: |
            export KUBECONFIG=$(pwd)/kubeconfig.yaml
            helm upgrade --install feedback ./helm/feedback-service

workflows:
  ci-cd:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
